task:
  name: Build (Mac OS)
  osx_instance:
    image: mojave-base
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  environment:
    AWS_ACCESS_KEY_ID: ENCRYPTED[d6846410e2da33aa651119e8e09943f81f565dc6b1d790f6fbd45fc21aa95110f3dc2cf6258479f7033187367a095050]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[d5dfb3a2248f55ea8051ddd80c1934b44f79fe1e6bef3b4f083b4215f9e2a84f94a097fc16eff6d0d6bc3d83fac64433]
  install_script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - curl -L https://releases.wezm.net/upload-to-s3/upload-to-s3-0.1.0-x86_64-apple-darwin.tar.gz | tar xzf - -C /usr/local/bin
  build_script: 'PATH="$HOME/.cargo/bin:$PATH" cargo build --release'
  publish_script:
    - export tarball="upload-to-s3-$(git rev-parse --short HEAD)-amd64-unknown-freebsd.tar.gz"
    - tar zcf "$tarball" -C target/release upload-to-s3
    - upload-to-s3 -b releases.wezm.net "$tarball" "upload-to-s3/$tarball"
  before_cache_script: rm -rf $CARGO_HOME/registry/index
